version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: just_coffee_db
    restart: always
    env_file: .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: just_coffee_api
    depends_on:
      - postgres
    env_file: .env
    ports:
      - "${PORT}:3000"
    volumes:
      - .:/app
    command: npm run start

volumes:
  postgres_data:
